{{- if .Values.controller.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
  name: {{ .Values.controller.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.controller.name }}
    giantswarm.io/service-type: "managed"
    k8s-app: {{ .Values.controller.k8sAppLabel }}
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: {{ .Values.controller.service.nodePorts.http }}
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    nodePort: {{ .Values.controller.service.nodePorts.https }}
    protocol: TCP
    targetPort: 443
  selector:
    k8s-app: {{ .Values.controller.k8sAppLabel }}
{{-  end }}
